version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes: 
      - mongo_db:/data/db
    
  foodcalApi:
    build: .
    image: arrin/foodcalapi
    ports:
      - 4000:3000
    volumes:
      - /usr/src/app/
    environment:
      ports: 3000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: Food_cal
      NAME: Foodcal
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}


      