version: "3.9"

services:
  model-api:
    build: .
    networks:
      - food-cal-model-and-service-api
    image: arrin/foodcal-model:1.0.0
    ports:
      - "6543:6543"

  foodcalApi:
    build: .
    networks:
      - food-cal-model-and-service-api
    image: arrin/foodcalapi
    ports:
      - 4000:3000

networks:
  food-cal-model-and-service-api:
