version: "3.9"

services:
  model-api:
    build: .
    networks:
      - food-cal-model-and-service-api
    image: arrin/foodcal-model:lastest
    ports:
      - "8000:8000"

  foodcalApi:
    build: .
    networks:
      - food-cal-model-and-service-api
    image: arrin/foodcalapi:lastest
    ports:
      - 4000:3000

networks:
  food-cal-model-and-service-api:
